### ISSUE TITLE
Rename

### ISSUE THREAD

**Issue by qubist** [holochain/soa-toolbox#3]
We were thinking of renaming this since it doesn't only scrape any more. Going with the theme of tree-related animals/people (climbing harness will be the name of an soa-navigator, etc.), some thoughts were:

* Arborist
* Toolbelt
* Arborist's toolbelt
* Monkey with a chainsaw

Discuss

**Comment by qubist** [comment]
I think I like arborist tool belt the best, thought it's not very succinct.

**Comment by qubist** [comment]
@zippy @samcooley Any ideas?

**Comment by samcooley** [comment]
> @zippy @samcooley Any ideas?

what is the scope of function imagined?  is it something that is expected to always/only be used with Acorn/SoA?  might it be used by something other than a human?  it is not about grafting or pruning, right?

**Comment by qubist** [comment]
> what is the scope of function imagined?

It's all of the different buttons that we are adding on to miro, so a bunch of different functionality:
* changing statuses of nodes on the tree (uncertain, small, done)
* Automatically recoloring the tree
* The xylem functionality (opposite of phloem, making GitHub issues out of nodes)

That's why I'm thinking something that holds a bunch of tools. I think it's ok to name some of these tools human-related things. In my mind we (developers, workers) are people caring for the tree, growing it. It does some of the work itself (phloem) but we also have to ~~prune~~ tweak the leafs and branches.

**Comment by qubist** [comment]
@samcooley and I have thought of a new name which covers the expanded scope of this repo: `soa-toolbox`

@Connoropolous How do you feel about this? Would you be willing to rename this repo? (I only have push access)

**Comment by Connoropolous** [comment]
I dig it. Yep, I can rename. Change you to admin too

**Comment by qubist** [comment]
Sweet, thank you Connor! Resolved!
